SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    -- 매출액 = 판매량(S.SALES) * 판매가(B.PRICE)의 총합
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM
    BOOK_SALES S
INNER JOIN
    BOOK B ON S.BOOK_ID = B.BOOK_ID
INNER JOIN
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE
    -- 2022년 1월 데이터만 필터링
    S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    -- 1. 저자 ID 오름차순 정렬
    A.AUTHOR_ID ASC,
    -- 2. 카테고리 내림차순 정렬
    B.CATEGORY DESC;