SELECT
    CHILD.ID,
    CHILD.GENOTYPE,
    PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA CHILD
INNER JOIN
    ECOLI_DATA PARENT ON CHILD.PARENT_ID = PARENT.ID
WHERE
    -- 자식의 형질이 부모의 형질을 '모두' 포함하는지 확인하는 비트 연산 조건
    (CHILD.GENOTYPE & PARENT.GENOTYPE) = PARENT.GENOTYPE
ORDER BY
    CHILD.ID ASC;